name: Recent Activity

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: cheesits456/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}